### ISSUE TITLE
I can't see and download the data 

### ISSUE THREAD

**Issue by S-anbarasu** [aws-samples/aws-machine-learning-university-accelerated-nlp#4]

**Comment by CiTRuS93** [comment]
Hey there!

if do u want to see the data you can either press the "view raw":
![image](https://user-images.githubusercontent.com/13310488/91711372-78099a00-eb8e-11ea-89a2-783cbe7c8a1c.png)


or "downlad":
![image](https://user-images.githubusercontent.com/13310488/91711218-37118580-eb8e-11ea-9c05-9c0397a44e75.png)

when you access the data files which in "comma separated value" format.

for example I opened the "AMAZON-REVIEW-DATA-CLASSIFICATION.csv" from the date folder:

![image](https://user-images.githubusercontent.com/13310488/91711573-c5860700-eb8e-11ea-9232-c47b78c397b4.png)

**Comment by cemsaz** [comment]
Thanks @CiTRuS93. Yes, @S-anbarasu, you can see the datasets under this path: https://github.com/aws-samples/aws-machine-learning-university-accelerated-nlp/tree/master/data and download them like @CiTRuS93 showed above.

**Comment by S-anbarasu** [comment]
@cemsaz bro i won't raw data and i can't download it second thing ![IMG_20200901_060805.jpg](https://user-images.githubusercontent.com/65596350/91782044-a1bbd300-ec19- # -11ea-9093-89c394a3e777.jpg) this
